---
deployment:
    tasks:
        - export DEPLOYPATH=/home/schnupf1/staging
        - export ENVIRONMENT=staging
        - cd $DEPLOYPATH
        - /opt/cpanel/ea-php82/root/usr/bin/php /opt/cpanel/composer/bin/composer
          install
        - yarn install
        - yarn build
        - /opt/cpanel/ea-php82/root/usr/bin/php artisan optimize
        - /opt/cpanel/ea-php82/root/usr/bin/php artisan config:cache
        - /opt/cpanel/ea-php82/root/usr/bin/php artisan event:cache
        - /opt/cpanel/ea-php82/root/usr/bin/php artisan route:cache
        - /opt/cpanel/ea-php82/root/usr/bin/php artisan view:cache
        - ln -s $DEPLOYPATH /home/schnupf1/www/$ENVIRONMENT
        - chmod 755 $DEPLOYPATH
