name: Deploy Laravel Application

on:
    workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DEPLOYPATH: /home/schnupf1/staging
      ENVIRONMENT: staging

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'  # Change to your required PHP version
        extensions: mbstring, intl, pdo, pdo_mysql
        tools: composer

    - name: Install Composer dependencies
      run: composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Change to your required Node.js version

    - name: Install Node.js dependencies
      run: yarn install

    - name: Build assets
      run: yarn build

    - name: Run Laravel optimizations
      run: |
        php artisan optimize
        php artisan config:cache
        php artisan event:cache
        php artisan route:cache
        php artisan view:cache

    - name: Run database migrations with seed
      run: php artisan migrate:refresh --seed

    - name: Deploy via SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_SERVER: ${{ secrets.SSH_SERVER }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts

        # Sync application files to the server
        rsync -avz --delete-after $GITHUB_WORKSPA
