name: Deploy Laravel Application

on:
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DEPLOYPATH: /home/schnupf1/staging
      ENVIRONMENT: staging

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, intl, pdo, pdo_mysql
        tools: composer

    - name: Install Composer dependencies
      run: composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Node.js dependencies
      run: yarn install

    - name: Build assets
      run: yarn build

    - name: Deploy via SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_SERVER: ${{ secrets.SSH_SERVER }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts

        # Sync application files to the server
        rsync -avz --delete-after $GITHUB_WORKSPACE/ $SSH_USER@$SSH_SERVER:$DEPLOYPATH

        # Run deployment commands on the server
        ssh $SSH_USER@$SSH_SERVER "ln -sfn $DEPLOYPATH /home/schnupf1/www/$ENVIRONMENT"
        ssh $SSH_USER@$SSH_SERVER "chmod 755 $DEPLOYPATH"

        # Run database migrations with seed on the server
        ssh $SSH_USER@$SSH_SERVER "cd $DEPLOYPATH && /opt/cpanel/ea-php82/root/usr/bin/php artisan migrate:refresh --seed"

        # Run Laravel optimizations on the server
        ssh $SSH_USER@$SSH_SERVER "cd $DEPLOYPATH && /opt/cpanel/ea-php82/root/usr/bin/php artisan optimize"
        ssh $SSH_USER@$SSH_SERVER "cd $DEPLOYPATH && /opt/cpanel/ea-php82/root/usr/bin/php artisan config:cache"
        ssh $SSH_USER@$SSH_SERVER "cd $DEPLOYPATH && /opt/cpanel/ea-php82/root/usr/bin/php artisan event:cache"
        ssh $SSH_USER@$SSH_SERVER "cd $DEPLOYPATH && /opt/cpanel/ea-php82/root/usr/bin/php artisan route:cache"
        ssh $SSH_USER@$SSH_SERVER "cd $DEPLOYPATH && /opt/cpanel/ea-php82/root/usr/bin/php artisan view:cache"
