name: Deploy Laravel Application

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Set environment-specific variables
      run: |
        if [ "${{ github.event.inputs.environment }}" == "staging" ]; then
            echo "APP_ENV=staging" >> $GITHUB_ENV
            echo "DEPLOYPATH=/home/schnupf1/staging" >> $GITHUB_ENV
        elif [ "${{ github.event.inputs.environment }}" == "production" ]; then
            echo "APP_ENV=production" >> $GITHUB_ENV
            echo "DEPLOYPATH=/home/schnupf1/production" >> $GITHUB_ENV
        fi

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, intl, pdo, pdo_mysql
        tools: composer

    - name: Get composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache composer dependencies
      uses: actions/cache@v3
      with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

    - name: Install Composer dependencies
      run: composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader --no-dev

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'

    - name: Get yarn cache directory
      id: yarn-cache
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

    - name: Cache yarn dependencies
      uses: actions/cache@v2
      with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

    - name: Install Node.js dependencies
      run: yarn install --frozen-lockfile --check-files

    - name: Build assets
      run: yarn build

    - name: Activate maintenance mode
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: cd ${{ env.DEPLOYPATH }} && php artisan down || true

    - name: Ensure deploy path exists on the server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_SERVER }}
        username: ${{ secrets.SSH_USER }}
        port: 22
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
            mkdir -p ${{ env.DEPLOYPATH }}

    - name: Sync application files to the server
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: --recursive --no-perms --no-owner --no-group --ignore-times --compress --verbose --delete --exclude-from=.rsyncignore
        remote_path: ${{ env.DEPLOYPATH }}
        remote_host: ${{ secrets.SSH_SERVER }}
        remote_port: 22
        remote_user: ${{ secrets.SSH_USER }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
        local_path: $GITHUB_WORKSPACE/

    - name: Create symlink and set permissions on the server
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ln -sfn ${{ env.DEPLOYPATH }} /home/schnupf1/www/${{ env.APP_ENV }}
            chmod 755 ${{ env.DEPLOYPATH }}

    - name: Ensure storage and cache directories exist and have proper permissions
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_SERVER }}
        username: ${{ secrets.SSH_USER }}
        port: 22
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
            cd ${{ env.DEPLOYPATH }}
            mkdir -p storage/framework/{sessions,views,cache}
            mkdir -p bootstrap/cache
            chmod -R 755 storage
            chmod -R 755 bootstrap/cache

    - name: Ready up application & disable maintenance mode
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_SERVER }}
        username: ${{ secrets.SSH_USER }}
        port: 22
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
            cd ${{ env.DEPLOYPATH }}
            rm -rf bootstrap/cache/*
            php artisan optimize:clear
            php artisan storage:link
            php artisan migrate --force
            php artisan auth:clear-resets
            php artisan optimize
            php artisan up

